### PR TITLE
execute connectivity check in ctor

### LINKED ISSUE #61: Connectivity IsConnected on Android only correct set when you change the state
Hi
first of all, thanks for the plugins! :)

I had some issues with the version 2.1 of the connectivity plugin on Android. I noticed that all the properties are false when you start the app even though I have an internet connection via cellular. When I 
disable and enable my mobile connection it turns correctly to true, but is false after the next restart.
Also, when I'm in the app and start wlan it turns to true correctly as well.

I've found the same issue on 2.0.1 version of the plugin. 

I have an HTC 10 with Android 6.0.1

### PR DESCRIPTION
**Pull request by NPadrutt**
This should prevent that the network information are not properly
initialized.

fix #61

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Can I get you to merge in master?

**Comment by NPadrutt** [comment]
like that? :)

**Comment by Cheesebaron** [comment]
Excellent. All green 😄

**Comment by NPadrutt** [comment]
Any plans to publish a nuget update with this included? :)

**Comment by Cheesebaron** [comment]
Isn't this out?

**Comment by NPadrutt** [comment]
regarding to nuget.org the last update was on the 5th december and the PR was merged on the 8th. So I assumed not yet ^^

**Comment by Cheesebaron** [comment]
Ah ok.

**Comment by Cheesebaron** [comment]
Should be in 2.2.1 momentarily 😄 Thanks!

**Comment by NPadrutt** [comment]
Great thabk you :)

**Pull request merged**
