### PR TITLE
WPF and Windows Store Implementations of Settings plugin

### PR DESCRIPTION
**Pull request by munkii**
I have added a WPF and WindowsStore implementation of your Settings PlugIn

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Windows Store was added some time ago. Wpf was merged in manually. Thanks!

**Comment by munkii** [comment]
Apologies for never getting around to updating the package files. Thanks
for merging

On 19 May 2015 at 12:30, Tomasz Cielecki <notifications@github.com> wrote:

> Windows Store was added some time ago. Wpf was merged in manually. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cheesebaron/Cheesebaron.MvxPlugins/pull/32#issuecomment-103450807>
> .
>



-- 
Patrick Long - Munkiisoft Ltd

**Comment by munkii** [comment]
I am obviously being an idiot here but seeing "Windows Store was added some time ago" I was expecting too see a Cheesebaron.MvxPlugins.Settings.WindowsStore in GitHub and Nuget. Where is it?

**Comment by Cheesebaron** [comment]
It is in WindowsCommon

**Pull request closed without merging**
