### PR TITLE
Updated FormsPresenters plug-in to latest Xamarin.Forms

### PR DESCRIPTION
**Pull request by MarcosCobena**

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Awesome thanks. I've added you as a collaborator, now you can commit directly if you want.

**Comment by MarcosCobena** [comment]
Hey Tomasz, thanks for adding me as collaborator!

Would you make the merge or want me to do it?

Also, I'd like to discuss how to achieve the NuGet packages, since it looks for me we should do something similar to MvvmCross in terms of adding a TODO dir. with instructions on which changes are needed to get it working.

**Comment by MarcosCobena** [comment]
Man, I've just done the PR manually. I think everything's OK, but please take a look in order to close this. Thanks!

**Comment by Cheesebaron** [comment]
Closing this PR as it has been merged manually.

Forms discussion continues in #34

Initial NuGet can be grabbed here: https://www.nuget.org/packages/Cheesebaron.MvxPlugins.FormsPresenters/0.0.1

**Pull request closed without merging**
